name: Deploy Docs
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - master
    paths:
      - docs-site/**
  pull_request:
    paths:
      - docs-site/**
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    # Deploy to Vercel Previews on pull request, push to master branch
    steps:
      - name: Get branch preview subdomain
        env:
          HEAD_REF: ${{ github.head_ref }}
          REF_NAME: ${{ github.ref_name }}
        if: |
          github.event_name == 'pull_request' || (
            github.event_name == 'push' && (
              github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-')
            )
          )
        run: |
          BRANCH_PREVIEW_SUBDOMAIN=$(echo "${HEAD_REF:-$REF_NAME}" | sed -e 's/[^a-zA-Z0-9-]/-/g; s/^-*//; s/-*$//' | cut -c1-63)
          BRANCH_PREVIEW_SUBDOMAIN=$(echo $BRANCH_PREVIEW_SUBDOMAIN | sed 's/--/-/g; s/-$//')
          echo "$BRANCH_PREVIEW_SUBDOMAIN"
          echo "BRANCH_PREVIEW_SUBDOMAIN=$BRANCH_PREVIEW_SUBDOMAIN" >> "${GITHUB_ENV}"

      - name: Get fetch depth
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV
          else
            echo "FETCH_DEPTH=1" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # TODO: Add linting back in once we have a linting workflow
      # - name: Lint Docs
      #   run: |
      #     cd docs-site
      #     yarn install
      #     yarn run lint

      # Commits to pull requests result in preview deployments
      - name: Publish Preview to Vercel
        uses: amondnet/vercel-action@v25
        if: |
          github.event_name == 'pull_request'
        with:
          github-comment: ${{ github.event.pull_request && env.CHANGES_ENTRY || true }}
          vercel-token: ${{ secrets.VERCEL_DEVTOOL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_COMPASS_DOCS_PROJECT_ID }}
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: docs-site

      # Pushes to `master` result in production deployments on the `docs.compass.dagster.io` domain
      - name: Publish Main Preview to Vercel
        uses: amondnet/vercel-action@v25
        if: |
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          github-comment: ${{ github.event.pull_request && env.CHANGES_ENTRY || true }}
          vercel-token: ${{ secrets.VERCEL_DEVTOOL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_COMPASS_DOCS_PROJECT_ID }}
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: docs.compass.dagster.io
          working-directory: docs-site
