compass_bot_token: {{ env('SLACK_BOT_TOKEN') }}
slack_signing_secret: {{ env('SLACK_SIGNING_SECRET', '') }}
slack_app_token: {{ env('SLACK_APP_TOKEN', '') }}

# Stripe Configuration (Stripe sandbox, e.g. not real customers/products etc)
stripe:
  token: {{ env('STRIPE_TOKEN') }}
  publishable_key: {{ env('STRIPE_PUBLISHABLE_KEY') }}
  free_product_id: prod_SzM13a3pwgpMB9
  starter_product_id: prod_SzM1oMuuv6VgSz
  team_product_id: prod_SzM1iicvcjBgR9
  design_partner_product_id: prod_SzmVzMSWuoRMlK
  default_product: free

ai_config:
  provider: bedrock
  aws_access_key: {{ env('AWS_ACCESS_KEY_ID') }}
  aws_secret_key: {{ env('AWS_SECRET_ACCESS_KEY') }}
  aws_region: "us-west-2"
  inference_profile_arn: arn:aws:bedrock:us-west-2:134857758541:inference-profile/us.anthropic.claude-sonnet-4-5-20250929-v1:0  

github:
  app_id: 1892808
  installation_id: 84214193
  private_key_path: /etc/secrets/dagster-compass-bot.2025-09-03.private-key.pem
  client_id: Iv23lipX3qxsBlN8kw72
  client_secret: {{ secret('github_client_secret', 'GITHUB_CLIENT_SECRET') }}
  rate_limiting_monitor_enabled: true

# Compass Dev Tools credentials
slack_admin_token: {{ secret('slack_admin_token', 'SLACK_ADMIN_TOKEN') }}
compass_dev_tools_bot_token: {{ secret('compass_dev_tools_bot_token', 'COMPASS_DEV_TOOLS_BOT_TOKEN') }}

secret_store:
  render_service_id: srv-d29oo8ndiees73d1d0ng
  render_api_key: {{ secret('render_api_key', 'RENDER_API_KEY') }}

# Temporal Configuration
temporal:
  type: cloud
  namespace: compass-prod.deae7
  endpoint: {{ env('TEMPORAL_ENDPOINT') }}
  api_key: {{ env('TEMPORAL_API_KEY') }}

db_config:
  # Storage Configuration - supports SQLite, PostgreSQL, and Redis:
  # For SQLite: sqlite:///absolute/path.db or ./relative/path.db
  # For Redis: redis://host:6379/0 or rediss://host:6379/0 (SSL)
  # For PostgreSQL: postgresql://user:password@host:5432/database
  database_uri: {{ env('DATABASE_URL') }}
  
http_port: {{ env('HTTP_PORT', '3000') }}
http_host: {{ env('HTTP_HOST', '0.0.0.0') }}
public_url: 'https://dagstercompass.com'
jwt_secret: {{ env('JWT_SECRET') }}
mode: http

# List of Dagster admin users to invite to newly created Slack teams
dagster_admins_to_invite:
  - dagstercompass@dagsterlabs.com

# Prospector Configuration
prospector_contextstore_repo: dagster-compass/shared-prospector-context
prospector_data_connection:
  type: bigquery
  config:
    location: us
    service_account_json_string: '{{ env('PROSPECTOR_DATA_BQ_JSON') }}'
  table_names: []

# Optional: Segment analytics write key for tracking events
# To enable: Install analytics-python dependency and configure below:
segment_write_key: {{ secret('segment_write_key', 'SEGMENT_WRITE_KEY') }}
